spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  freemaker:
    cache: false