spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  mustache:
    cache: false
  profiles:
    include: oauth

images:
  load:
    path: C:\Users\msyu\IdeaProjects\lottsgram-webservice\src\main\resources\static\images
  save:
    path: /images